import type { ParseState } from "./codex-parse-state.js";
import type { SessionDetailLevel } from "./session-detail-metrics.js";

/** Fresh mutable state for one bounded transcript fold. */
export function createParseState(detail: SessionDetailLevel): ParseState {
  return {
    abortedTurns: 0,
    calls: detail === "calls" ? [] : undefined,
    commands: new Map(),
    compactions: 0,
    completedTurns: 0,
    contextWindow: undefined,
    cwd: undefined,
    editFiles: 0,
    editsApplied: 0,
    editsFailed: 0,
    endedAt: undefined,
    firstMs: undefined,
    git: { branch: undefined, commitHash: undefined, repositoryUrl: undefined },
    greenIteration: undefined,
    initialContextTokens: undefined,
    initialPromptChars: 0,
    initialPromptLines: [],
    invalidValues: 0,
    internalApprovalReview: false,
    interventions: [],
    largestToolOutputChars: 0,
    lastMs: undefined,
    malformedLines: 0,
    model: undefined,
    openTurn: undefined,
    outcomes: [],
    peakRequestTokens: 0,
    pending: new Map(),
    promptOpen: true,
    pullRequests: new Set(),
    quota: undefined,
    recognized: 0,
    sessionId: undefined,
    shellSessions: new Map(),
    startedAt: undefined,
    tokens: undefined,
    tokensAtFirstGreen: undefined,
    tools: new Map(),
    toolOutputChars: 0,
    turnById: new Map(),
    turnList: [],
    turns: 0,
    turnsTruncated: false,
    userMessages: 0,
    validationAttempts: 0,
    validationFailures: 0,
    validationTimeMs: 0,
    workItems: new Set(),
  };
}
